name = "bitespeed-project"
main = "src/index.ts"
compatibility_date = "2025-05-29"

[[d1_databases]]
binding = "DB"
database_name = "bitespeed-db"
database_id = "cf9d780f-e10d-4603-882e-4a9646928a18" 